### ISSUE TITLE
Example output file?

### ISSUE THREAD

**Issue by stianlagstad** [Kingsford-Group/squid#20]
Hi,

I would like to know if the output data that SQUID produces can be used with https://github.com/stianlagstad/chimeraviz. Do you have any example output files that you can share?

Thank you!

**Comment by Congm12** [comment]
Hi,

Please see the following example of output file in the attachment of an HCC1954 sample using GRCh37 genome. The meaning of each column is in the Output Specification section. 

[hcc1954_sv.txt](https://github.com/Kingsford-Group/squid/files/4331403/hcc1954_sv.txt)

**Comment by stianlagstad** [comment]
Thank you very much. Is it alright if I include that file in the chimeraviz package, as example data? If ok with you, I'll add that in this PR: https://github.com/stianlagstad/chimeraviz/pull/79

**Comment by Congm12** [comment]
That's totally fine.

**Comment by stianlagstad** [comment]
Thanks again!
