### ISSUE TITLE
Parameter recommendations for benign tumor types

### ISSUE THREAD

**Issue by biobenkj** [Kingsford-Group/squid#6]
The software is fantastic and has been very easy to use! I am opening an issue to ask what some parameter recommendations would be for clonal benign tumor types? Specifically, I'm looking at the -r option for normal/tumor cell ratio. I appreciate your time and any insight.

**Comment by Congm12** [comment]
I would think benign tumor has less intra-heterogeneity compared to malignant tumor, so each TSV will get concentrated support from tumor cells. I would suggest setting r to be 1 or 2 to ensure precision.

**Comment by biobenkj** [comment]
Excellent. Thanks!
