### ISSUE TITLE
Question: Does SQUID accept STAR `WithinBAM` output?

### ISSUE THREAD

**Issue by fgvieira** [Kingsford-Group/squid#8]
Dear all,

I've been trying to get my input files for SQUID, but I am not sure about the input. As far as I can see, SQUID accepts two types of input:

- STAR: separate alignment and chimeric BAM files 
- BWA: combined BAM file of both concordant and discordant alignments

However, STAR also allow for a combined output (`--chimOutType WithinBAM`, either `HardClip` or `SoftClip`). Is this format compatible with SQUID BWA input (`--bwa` option)? And should it be `HardClip` or `SoftClip`?

thanks,

**Comment by Congm12** [comment]
For the time being, it is recommended to separate chimeric reads and concordant reads for STAR. For chimeric split-read alignments, there are multiple SAM records corresponding to one paired-end read, however only one record is marked as chimeric. This may lead to erroneous or missing edges in SQUID's segment graph when the records are mixed with all other concordant SAM records, and finally reduces the accuracy. So when you are STAR available, it is recommended to NOT use WithinBam option.

**Comment by fgvieira** [comment]
ok, thanks!
